#!/bin/sh

ip=$(hostname -i)
set -- $ip
ip1=$1
ip2=$2
cfg="/etc/dnstap.conf"
cfg_second="/etc/dnstap_second.conf"
echo "Container IP: $ip" 
if [[ "$DEBUG" -eq 1 ]]; then echo "DEBUG MODE on"; fi
if [[ "$SECOND_TUNNEL" -eq 1 ]]; then echo "SECOND TUNNEL MODE on"; fi
if [[ "$FALLBACK_UPSTEAM" -eq 1 ]]; then echo "FALLBACK UPSTEAM on"; fi
echo ""
echo "Starting dnstap server..."
mkdir -p /data/cache
if [ ! -f "/data/domains.txt" ]; then echo "example.com" > /data/domains.txt; fi
sed -i "s/ttl = \"[^\"]*\"/ttl = \"$TTL\"/g" "$cfg"
sed -i "s/routerID = \"\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}\"/routerID = \"$ip1\"/g" "$cfg"
sed -i "s/sourceIP = \"\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}\"/sourceIP = \"$ip1\"/g" "$cfg"
sed -i "s/nextHop = \"\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}\"/nextHop = \"$ROUTE\"/g" "$cfg"
sed -i "s/peers = \[\"\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}\"\]/peers = [\"$BIRD\"]/g" "$cfg"
if [[ "$SECOND_TUNNEL" -eq 1 ]]; then
        if [ ! -f "/data/domains_second.txt" ]; then echo "example.ru" > /data/domains_second.txt;  fi
        sed -i "s/ttl = \"[^\"]*\"/ttl = \"$TTL\"/g" "$cfg_second"
        sed -i "s/routerID = \"\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}\"/routerID = \"$ip2\"/g" "$cfg_second"
        sed -i "s/sourceIP = \"\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}\"/sourceIP = \"$ip2\"/g" "$cfg_second"
        sed -i "s/nextHop = \"\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}\"/nextHop = \"$ROUTE_SECOND\"/g" "$cfg_second"
        sed -i "s/peers = \[\"\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}\"\]/peers = [\"$BIRD\"]/g" "$cfg_second"
fi
if [[ "$DEBUG" -eq 1 ]]; then
        mkdir -p /data/logs
        LOGDNSSTAP="/data/logs/dnstap.log"
        echo "dnstap logs save in $LOGDNSSTAP"
else
        LOGDNSSTAP="/dev/null"
fi
dnstap-bgp -config /etc/dnstap.conf > $LOGDNSSTAP 2>&1 &
if [[ "$SECOND_TUNNEL" -eq 1 ]]; then
        echo ""
        echo "Starting dnstap second server..."
        if [[ "$DEBUG" -eq 1 ]]; then
                LOGDNSSTAP_SECOND="/data/logs/dnstap_second.log"
                echo "dnstap second logs save in $LOGDNSSTAP_SECOND"
        else
                LOGDNSSTAP_SECOND="/dev/null"
        fi
        dnstap-bgp -config /etc/dnstap_second.conf > $LOGDNSSTAP_SECOND 2>&1 &
fi
sleep 5
echo ""
echo "Starting dnsdist server..."
sed -i "1c\setLocal(\"$ip1:53\")" /etc/dnsdist.conf
if [[ -n "${UPSTREAM:-}" && -n "${UPSTREAM_IP:-}" ]]; then
        sed -i "5c\newServer({address=\"$UPSTREAM_IP\", tls=\"openssl\", subjectName=\"$UPSTREAM\", dohPath=\"/dns-query\", validateCertificates=true, checkInterval=60, maxCheckFailures=5})" /etc/dnsdist.conf
fi
if [[ "$FALLBACK_UPSTEAM" -eq 1 ]]; then sed -i "6c\FALLBACK_UPSTEAM = 1" /etc/dnsdist.conf; fi
if [[ "$SECOND_TUNNEL" -eq 1 ]]; then sed -i "7c\SECOND_TUNNEL = 1" /etc/dnsdist.conf; fi
if [[ "$DEBUG" -eq 1 ]]; then
        LOGDNSDIST="/data/logs/dnsdist.log"
        echo "dnstap logs save in $LOGDNSDIST"
        dnsdist -v --disable-syslog --supervised > $LOGDNSDIST 2>&1
else
        dnsdist --disable-syslog --supervised
fi