#!/bin/sh

ip=$(hostname -i)
ipgw=$(ip r | awk '/default/ {print $3}')
cfg="/etc/bird.conf"
echo "Container IP: $ip" 
echo "Container gateway IP: $ipgw"
echo ""
echo "Starting bird server..."
mkdir -p /data/static /data/static_second
sed -i "s/router id \([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}/router id $ip/g" "$cfg"
sed -i "s/source address \([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}/source address $ip/g" "$cfg"
sed -i "s/neighbor \([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\} as 65010/neighbor $ipgw as 65010/g" "$cfg"
sed -i "s/neighbor \([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\} as 65000/neighbor $DNSTAP as 65000/g" "$cfg"
sed -i "s/neighbor \([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\} as 65001/neighbor $DNSTAP_SECONDIP as 65001/g" "$cfg"
sed -i "/proto = \"first\"/,/accept;/s/bgp_next_hop = \([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}\+;/bgp_next_hop = $ROUTE;/" "$cfg"
sed -i "/proto = \"second\"/,/accept;/s/bgp_next_hop = \([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}\+;/bgp_next_hop = $ROUTE_SECOND;/" "$cfg"
bird -f